runtime: nodejs10
instance_class: F2






env_variables:
  CLOUD_BUCKET: "prueba-pp"
  process.env.MONGO_URI: "mongodb://fjcapelo:Aitornacho66@ds243212.mlab.com:43212/database1"
  process.env.CLIENT_ID: "219758474264-vh1bibcphgvbc32km508lubtqkanikf1.apps.googleusercontent.com"
  process.env.YOUR_CLIENT_ID: "AIzaSyBNtD9D_96Y88nf9IHcRsQkt9o-7caOWHQ"
  GOOGLE_CLOUD_PROJECT_ID: "rayos-214316"
  process.env.NODE_ENV: process.env.NODE_ENV




  handlers:
  - url: /public/imagenes/
    static_files: favicon.ico

  - url: /js
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto